### ISSUE TITLE
Maintenance: Auto remove mongodb backups on clinical-db

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/backup#12]
Situation: mongobar is creating a weekly dump from mongo. Stored at `/var/lib/mongodbhc/backups`.

Problem: all backups remain. Ideally, backups should be removed after a certain date. See *AMS#1170     Server maintenance and backup*, section 3.5.

How do we know that a backup is on tape?

The removal process should be be done for:
- mongo
- mysql

See card #1705   for a more detailed explanation on locations.

**Comment by emiliaol** [comment]
Awesome, thanks
